name: wordpress-vinyl
type: service
from: vinyl
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.11"
title: Vinyl (WordPress)


labels:
- wordpress
- varnish
- vinyl

configs:
- name: wordpress
  title: WordPress preset
  filepath: /etc/gotpl/preset/wordpress.vcl.tmpl
  default:
    source: image
    filepath: /etc/gotpl/presets/wordpress.vcl.tmpl

env:
- name: VARNISH_CONFIG_PRESET
  value: wordpress
