name: wordpress-vinyl
type: service
from: vinyl
fromVersion: "^1.0.0"
title: Vinyl (WordPress)

    
labels:
- wordpress
- varnish
- vinyl

configs:
- name: wordpress
  title: Drupal preset
  filepath: /etc/gotpl/preset/wordpress.vcl.tmpl
  config: wordpress.vcl.tmpl

env:
- name: VARNISH_CONFIG_PRESET
  value: wordpress
